name:                dbmonitor
version:             0.1.0
github:              "viviag/dbmonitor"
license:             BSD3
author:              "Vitalii Guzeev"
maintainer:          "viviag@yandex.ru"
copyright:           "2021-2022 Vitalii Guzeev"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Data consistency alerting for PostgreSQL
category: Monitoring, Database

description: Tool performing periodic checks of data invariants which are hard or impossible to be imposed by constraints. For Postgres only.

dependencies:
- base >= 4.18.2 && < 4.19
- optparse-applicative >= 0.18.1 && < 0.19

library:
  source-dirs: src
  dependencies:
  - ansi-terminal >= 1.0.2 && < 1.1
  - async >= 2.2.5 && < 2.3
  - bytestring >= 0.11.5 && < 0.12
  - filepath >= 1.4.200 && < 1.5
  - mtl >= 2.3.1 && < 2.4
  - stm >= 2.5.1 && < 2.6
  - text >= 2.0.2 && < 2.1
  - dhall >= 1.42.1 && < 1.43
  - unordered-containers >= 0.2.20 && < 0.3
  - vector >= 0.13.1 && < 0.14
  - time >= 1.12.2 && < 1.13
  - directory >= 1.3.8 && < 1.4
  - fsnotify >= 0.4.1 && < 0.5
  - monad-control >= 1.0.3 && < 1.1
  - transformers-base >= 0.4.6 && < 0.5
  - hasql >= 1.6.4 && < 1.7
  - lifted-base >= 0.2.3 && < 0.3
  - telegram-bot-api >= 7.0 && < 7.1
  ghc-options:
  - -Wall
  - -Wunused-packages
  - -Werror
  - -Wwarn=unused-packages

executables:
  dbmonitor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
#    - -eventlog
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dbmonitor
