name:                dbmonitor
version:             0.1.0
github:              "viviag/dbmonitor"
license:             BSD3
author:              "Vitalii Guzeev"
maintainer:          "viviag@yandex.ru"
copyright:           "2021-2022 Vitalii Guzeev"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Data consistency alerting for PostgreSQL
category: Monitoring, Database

description: Tool performing periodic checks of data invariants which are hard or impossible to be imposed by constraints. For Postgres only.

dependencies:
- ansi-terminal        >= 0.11.3
- base                 >= 4.12.0
- async                >= 2.2.2
- bytestring           >= 0.10.8
- text                 >= 1.2.3
- stm                  >= 2.5.0
- dhall                >= 1.40.2
- time                 >= 1.8.0
- unordered-containers >= 0.2.10
- vector               >= 0.12.0
- filepath             >= 1.4.2
- directory            >= 1.3.3
- mtl                  >= 2.2.2
- optparse-applicative >= 0.16.1
- hasql                >= 1.4.4
- fsnotify             >= 0.3.0
- lifted-base          >= 0.2.3
- monad-control        >= 1.0.3
- transformers-base    >= 0.4.6
- telegram-bot-simple  >= 0.4.5
- telegram-bot-api
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wunused-packages
  - -Werror
  - -Wwarn=unused-packages

executables:
  dbmonitor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
#    - -eventlog
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dbmonitor
